export const AUTHENTICATE_USER = 'STORE_USER';

//newsletter actions
export const SET_NEWSLETTERS = 'SET_NEWSLETTERS';
export const FETCH_NEWSLETTER_ID = 'FETCH_NEWSLETTER_ID';


//REQUESTS ACTIONS
export const CHANGE_SELECTED_REQUEST_TYPE ='CHANGE_SELECTED_REQUEST_TYPE';